/**
 * Axe-core rule ID to WCAG 2 Level mapping.
 * Derived from axe-core rule descriptions (wcag2a, wcag2aa, wcag2aaa, wcag21aa, cat.apca).
 * Unknown rules remain Unknown in detectWcagLevel.
 */
export type WcagLevel = 'A' | 'AA' | 'AAA' | 'APCA';

export const AXE_RULE_WCAG_LEVEL: Record<string, WcagLevel> = {
    // WCAG 2.0 Level A
    'area-alt': 'A',
    'aria-allowed-attr': 'A',
    'aria-braille-equivalent': 'A',
    'aria-command-name': 'A',
    'aria-conditional-attr': 'A',
    'aria-deprecated-role': 'A',
    'aria-hidden-body': 'A',
    'aria-hidden-focus': 'A',
    'aria-input-field-name': 'A',
    'aria-meter-name': 'A',
    'aria-progressbar-name': 'A',
    'aria-prohibited-attr': 'A',
    'aria-required-attr': 'A',
    'aria-required-children': 'A',
    'aria-required-parent': 'A',
    'aria-roles': 'A',
    'aria-tab-name': 'A',
    'aria-toggle-field-name': 'A',
    'aria-tooltip-name': 'A',
    'aria-valid-attr-value': 'A',
    'aria-valid-attr': 'A',
    'blink': 'A',
    'button-name': 'A',
    'bypass': 'A',
    'definition-list': 'A',
    'dlitem': 'A',
    'document-title': 'A',
    'duplicate-id-aria': 'A',
    'form-field-multiple-labels': 'A',
    'frame-focusable-content': 'A',
    'frame-title-unique': 'A',
    'frame-title': 'A',
    'html-has-lang': 'A',
    'html-lang-valid': 'A',
    'html-xml-lang-mismatch': 'A',
    'image-alt': 'A',
    'input-button-name': 'A',
    'input-image-alt': 'A',
    'label': 'A',
    'link-in-text-block': 'A',
    'link-name': 'A',
    'list': 'A',
    'listitem': 'A',
    'marquee': 'A',
    'meta-refresh': 'A',
    'nested-interactive': 'A',
    'object-alt': 'A',
    'role-img-alt': 'A',
    'scrollable-region-focusable': 'A',
    'select-name': 'A',
    'server-side-image-map': 'A',
    'summary-name': 'A',
    'svg-img-alt': 'A',
    'td-headers-attr': 'A',
    'th-has-data-cells': 'A',
    'video-caption': 'A',
    // WCAG 2.0 Level AA
    'color-contrast': 'AA',
    'meta-viewport': 'AA',
    'valid-lang': 'AA',
    // WCAG 2.1 Level A & AA
    'autocomplete-valid': 'AA',
    'avoid-inline-spacing': 'AA',
    // WCAG 2.2
    'target-size': 'AA',
    'focus-not-obscured': 'AA',
    'focus-not-obscured-minimum': 'AA',
    'focus-not-obscured-enhanced': 'AAA',
    // WCAG 2.x AAA & Experimental
    'color-contrast-enhanced': 'APCA',
    'identical-links-same-purpose': 'AAA',
    'meta-refresh-no-exceptions': 'AAA',
    'css-orientation-lock': 'AA',
    'label-content-name-mismatch': 'A',
    'p-as-heading': 'A',
    'table-fake-caption': 'A',
    'td-has-header': 'A',
    // Deprecated (still map for existing results)
    'aria-roledescription': 'A',
    'audio-caption': 'A',
    'duplicate-id-active': 'A',
    'duplicate-id': 'A',
};
